### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by masakinihirota** [ruby-formatter/rufo#167]
You've found a bug!
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it

```
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:3291:in `rstrip': invalid byte sequence in Windows-31J (ArgumentError)
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:3291:in `block in consume_end_of_line'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:3146:in `loop'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:3146:in `consume_end_of_line'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:530:in `block in visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:496:in `each'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:496:in `each_with_index'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:496:in `visit_exps'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:195:in `visit'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/formatter.rb:173:in `format'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/command.rb:134:in `format'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/command.rb:49:in `format_stdin'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/command.rb:39:in `run'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/lib/rufo/command.rb:12:in `run'
	from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/rufo-0.6.0/exe/rufo:4:in `<top (required)>'
	from C:/Ruby26-x64/bin/rufo:23:in `load'
	from C:/Ruby26-x64/bin/rufo:23:in `<main>'
```

**Comment by gingermusketeer** [comment]
@masakinihirota Are you able to share the file that caused this issue, or a minimal version of it that causes the same issue? Looks like it is something to do with the file encoding.

**Comment by gingermusketeer** [comment]
@masakinihirota Please reopen this if you find the above information.
