### ISSUE TITLE
invalid byte sequence in Windows-31J (ArgumentError)

### ISSUE THREAD

**Issue by Gigacee** [ruby-formatter/rufo#181]
ruby 2.5.5p157 
rufo 0.7.0
Visual Studio Code 1.35.1

```
You've found a bug!
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3301:in `rstrip': invalid byte sequence in Windows-31J (ArgumentError)
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3301:in `block in consume_end_of_line'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3156:in `loop'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:3156:in `consume_end_of_line'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:492:in `visit_exps'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:195:in `visit'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/formatter.rb:173:in `format'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/command.rb:134:in `format'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/command.rb:49:in `format_stdin'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/command.rb:39:in `run'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/lib/rufo/command.rb:12:in `run'
	from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/rufo-0.7.0/exe/rufo:4:in `<top (required)>'
	from C:/Ruby25-x64/bin/rufo:23:in `load'
	from C:/Ruby25-x64/bin/rufo:23:in `<main>'
```

**Comment by Gigacee** [comment]
1 行目に以下を記述すると、発生しなくなりました。
The following in the first line no longer occurs:

`# encoding: utf-8`

**Comment by gingermusketeer** [comment]
Hi, I have not been able to reproduce this issue. Are you able to share a file that causes rufo to fail?

**Comment by Gigacee** [comment]
I tried again to format my ruby documents without `# encoding: utf-8` on the latest environment, This error no longer occurs.
Thanks!

最新バージョンで再度試してみたところ、エラーが発生しなくなっていました。

rufo v0.7.0
ruby 2.6.5p114
Visual Studio Code v1.40.1
