### ISSUE TITLE
`scan': invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by kaitaku** [ruby-formatter/rufo#245]
Hi

The error below occurs even though the erb file is uft-8.

/Users/xxxxx/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/erb.rb:454:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
	from /Users/xxxxx/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/erb.rb:454:in `trim_line2'
	from /Users/xxxxx/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/erb.rb:411:in `call'
	from /Users/xxxxx/.rvm/rubies/ruby-2.5.7/lib/ruby/2.5.0/erb.rb:411:in `scan'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/gems/rufo-0.12.0/lib/rufo/erb_formatter.rb:74:in `process_erb'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/gems/rufo-0.12.0/lib/rufo/erb_formatter.rb:36:in `format'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/gems/rufo-0.12.0/lib/rufo/command.rb:146:in `format'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/gems/rufo-0.12.0/lib/rufo/command.rb:49:in `format_stdin'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/gems/rufo-0.12.0/lib/rufo/command.rb:38:in `run'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/gems/rufo-0.12.0/lib/rufo/command.rb:12:in `run'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/gems/rufo-0.12.0/exe/rufo:4:in `<top (required)>'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/bin/rufo:23:in `load'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/bin/rufo:23:in `<main>'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/bin/ruby_executable_hooks:24:in `eval'
	from /Users/xxxxx/.rvm/gems/ruby-2.5.7/bin/ruby_executable_hooks:24:in `<main>'

**Comment by gingermusketeer** [comment]
@kaitaku Thanks for opening an issue. It looks like you are piping the code into rufo? Are you able to pipe it into `ruby -e "puts STDIN.read.encoding"` and send me the output? 

Strange that the code is not being treated as UTF8 by default.
