### ISSUE TITLE
Bug found when setting classes with def

### ISSUE THREAD

**Issue by theocodes** [ruby-formatter/rufo#280]
Hey there,

Just reporting a bug I found.. This got me scratching my head as I was not familiar with the syntax, but throwing the below in a class causes the error to happen.

```ruby
def self.classes = some_value
```

Apparently it's valid because is currently working in our codebase but can't say I'd come across it before... Anyhow, I figured if ruby supports it, so should the formatter 😄 

Please let me know if you have any questions 👍 

Thanks!

Here's the trace:
```
You've found a bug!
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it
/home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3582:in `bug': unexpected node: vcall at [[49, 19], :on_op, "=", BEG] at [[49, 19], :on_op, "=", BEG] (Rufo::Bug)
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:193:in `visit'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:526:in `block (2 levels) in visit_exps'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3699:in `push_node'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:525:in `block in visit_exps'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each_with_index'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `visit_exps'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3445:in `indent_body'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1578:in `visit_bodystmt'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:380:in `visit'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2088:in `visit_def_from_name'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2028:in `block in visit_def_with_receiver'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3707:in `push_hash'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2027:in `visit_def_with_receiver'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:412:in `visit'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:526:in `block (2 levels) in visit_exps'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3699:in `push_node'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:525:in `block in visit_exps'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each_with_index'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `visit_exps'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3467:in `block in indent_body'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3391:in `indent'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3466:in `indent_body'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1578:in `visit_bodystmt'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:380:in `visit'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1990:in `block in visit_module'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3714:in `push_type'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:1983:in `visit_module'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:400:in `visit'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:526:in `block (2 levels) in visit_exps'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3699:in `push_node'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:525:in `block in visit_exps'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `each_with_index'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:504:in `visit_exps'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:201:in `visit'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:177:in `format'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:146:in `format'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:49:in `format_stdin'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:38:in `run'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/command.rb:12:in `run'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/exe/rufo:4:in `<top (required)>'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/bin/rufo:25:in `load'
	from /home/theocodes/.asdf/installs/ruby/3.1.2/bin/rufo:25:in `<main>'
```

**Comment by kzkn** [comment]
The problem was fixed in 0.14.0.

```
$ ./exe/rufo --version
rufo 0.13.0
$ echo 'def self.classes = some_value' | ./exe/rufo
You've found a bug!
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it
/home/kazuki/ghq/github.com/ruby-formatter/rufo/lib/rufo/formatter.rb:3582:in `bug': unexpected node: vcall at [[1, 17], :on_op, "=", BEG] at [[1, 17], :on_op, "=", BEG] (Rufo::Bug)
        from /home/kazuki/ghq/github.com/ruby-formatter/rufo/lib/rufo/formatter.rb:193:in `visit'
        from /home/kazuki/ghq/github.com/ruby-formatter/rufo/lib/rufo/formatter.rb:526:in `block (2 levels) in visit_exps'
        from /home/kazuki/ghq/github.com/ruby-formatter/rufo/lib/rufo/formatter.rb:3699:in `push_node'
        from /home/kazuki/ghq/github.com/ruby-formatter/rufo/lib/rufo/formatter.rb:525:in `block in visit_exps'
        from /home/kazuki/ghq/github.com/ruby-formatter/rufo/lib/rufo/formatter.rb:504:in `each'
(snip)
```

```
$ ./exe/rufo --version
rufo 0.14.0
$ echo 'def self.classes = some_value' | ./exe/rufo
def self.classes = some_value
```

Please try the latest version.
