### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by gbisheimer** [ruby-formatter/rufo#316]
I'm using VS code rufo extension to format my code ruby code.

I've got this error message:

```
You've found a bug!
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it
/home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:453:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:453:in `trim_line2'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:410:in `call'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:410:in `scan'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/erb_formatter.rb:74:in `process_erb'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/erb_formatter.rb:36:in `format'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/command.rb:146:in `format'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/command.rb:49:in `format_stdin'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/command.rb:38:in `run'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/command.rb:12:in `run'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/exe/rufo:4:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/3.1.2/bin/rufo:25:in `load'
	from /home/ubuntu/.rbenv/versions/3.1.2/bin/rufo:25:in `<main>'
```

Searching for a solution, I found this [post](https://stackoverflow.com/questions/17031651/rails-invalid-byte-sequence-in-us-ascii-argument-error-when-i-run-rake-dbsee) in SO.

I solved my problem by editing the file /home/ubuntu/.rbenv/versions/3.1.2/bin/rufo:25 in my system and added the following lines before line 25:

```
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8
```

Now, the formatter works as expected.

**Comment by kzkn** [comment]
Please show minimal reproducible example?

**Comment by gbisheimer** [comment]
This file uses non-US characters:
```ruby
columns do
  column do
    panel "Batchs" do
      table_for(@batch_logs, sortable:false) do
        column :created_at
        column "Setpoint", :peso_setpoint do |bl|
          "#{bl.peso_setpoint} #{Settings.unit_statistics.humanize}"
        end
        column "Medición", :peso_dosificado do |bl|
          "#{bl.peso_dosificado} #{Settings.unit_statistics.humanize}"
        end
      end
    end
  end
end
```

I'm getting this error:
![image](https://github.com/ruby-formatter/rufo/assets/3077123/66fc80d0-e4c8-4554-8dbc-bfe8771fe53e)

The responsible is the accented character in word **Medición**

Hope it helps.

**Comment by kzkn** [comment]
@gbisheimer 
I have tried to reproduce it but was not.

```
$ rufo --version
rufo 0.16.3

$ cat 316.erb
<% columns do
    column do
      panel "Batchs" do
        table_for(@batch_logs, sortable: false) do
          column :created_at
          column "Setpoint", :peso_setpoint do |bl|
            "#{bl.peso_setpoint} #{Settings.unit_statistics.humanize}"
          end
          column "Medición", :peso_dosificado do |bl|
            "#{bl.peso_dosificado} #{Settings.unit_statistics.humanize}"
          end
        end
      end
    end
  end %>

$ rufo 316.erb
$ echo $?
0
```

Does this same operation reproduce the original error in your environment?

**Comment by gbisheimer** [comment]
I'm using Rufo 0.15.1.
I've just tested it from the command line, and it works ok. But when I format the the same file from VSCode, it gives me this:
```
You've found a bug!
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it
/home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:453:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:453:in `trim_line2'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:410:in `call'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:410:in `scan'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/erb_formatter.rb:74:in `process_erb'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/erb_formatter.rb:36:in `format'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/command.rb:146:in `format'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/command.rb:49:in `format_stdin'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/command.rb:38:in `run'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/lib/rufo/command.rb:12:in `run'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.15.1/exe/rufo:4:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/3.1.2/bin/rufo:28:in `load'
	from /home/ubuntu/.rbenv/versions/3.1.2/bin/rufo:28:in `<main>'
```

I also updated the gem to version 0.16.3 and tried again, having the same error:
```
You've found a bug!
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it
/home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:453:in `scan': invalid byte sequence in US-ASCII (ArgumentError)
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:453:in `trim_line2'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:410:in `call'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/3.1.0/erb.rb:410:in `scan'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.16.3/lib/rufo/erb_formatter.rb:74:in `process_erb'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.16.3/lib/rufo/erb_formatter.rb:36:in `format'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.16.3/lib/rufo/command.rb:146:in `format'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.16.3/lib/rufo/command.rb:49:in `format_stdin'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.16.3/lib/rufo/command.rb:38:in `run'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.16.3/lib/rufo/command.rb:12:in `run'
	from /home/ubuntu/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.16.3/exe/rufo:4:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/3.1.2/bin/rufo:25:in `load'
	from /home/ubuntu/.rbenv/versions/3.1.2/bin/rufo:25:in `<main>'
```

It seems that VS Code changes the encoding before calling rufo formatter. Searching in code I found [this lines](https://github.com/jnbt/vscode-rufo/blob/84b42ef811d496e38e3abf809f988fb27d193f11/src/formatter/rufo.ts#L78-L79) that may be have something to do with this problem.

**Comment by gbisheimer** [comment]
I checked the value of Encoding.default_external and Encoding.default_internal when calling rufo from the terminal and from VS-Code.

From terminal:
```
Encoding.default_external: UTF-8
Encoding.default_internal:
```

From VS-Code
```
Encoding.default_external: US-ASCII
Encoding.default_internal:
```

Do you know if this can be changed from VS-Code settings?

**Comment by gbisheimer** [comment]
I'm sorry... I just realized that I'm posting this on the wrong repo.
