### ISSUE TITLE
Got "You've found a bug!"

### ISSUE THREAD

**Issue by kurmasz** [ruby-formatter/rufo#318]
Received this error message:

`You've found a bug! Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it /Users/kurmasz/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3582:in `bug': Expected token on_kw, not on_ident at [[266, 9], :on_ident, "quarter", END|LABEL] (Rufo::Bug) from /Users/kurmasz/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3577:in `check' from /Users/kurmasz/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:3153:in `consume_keyword' from /Users/kurmasz/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2907:in `visit_case' from /Users/kurmasz/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:390:in `visit' from /Users/kurmasz/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rufo-0.13.0/lib/rufo/formatter.rb:2851:in `visit_if_or_unless' from /Users/kurmasz/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3...`

when VSCode ran the formatter on this code:
```

require "test_helper"

class EntryAnalyzerTest < ActiveSupport::TestCase
  def make(id, user, year, month, day, segment, categories)
    e = Entry.new(id: id, user: user, date: Date.new(year, month, day), segment: segment)
    categories.each_with_index do |category_id, index|
      c = category_id.nil? ? nil : Category.find(category_id)
      e.set_category(index, c)
    end
    e.save!
    e
  end

  def setup
    @u1 = users :bob
    @u2 = users :joe

    # make sure the id and date doesn't conflict with the fixtures!
    @entries = [
      make(51, @u1, 2012, 1, 10, 3, [1, 2, 3, 3, 4]),
      make(52, @u1, 2012, 1, 10, 4, [5, 4, 3, 3, 2]),
      make(53, @u1, 2012, 1, 11, 3, [1, 2, 3, 3, 3]),
      make(54, @u1, 2012, 1, 11, 4, [5, 4, 3, 3, 3]),

      make(55, @u2, 2012, 1, 10, 3, [11, 12, 13, 13, 14]),
      make(56, @u2, 2012, 1, 10, 4, [15, 14, 13, 13, 12]),
      make(57, @u2, 2012, 1, 11, 3, [11, 12, 13, 13, 13]),
      make(58, @u2, 2012, 1, 11, 4, [15, 14, 13, 13, 13]),
    ]
  end

  #
  # parse_time
  #

  test ".parse_time handles valid input" do
    tests = {
      "0:00" => [0, 0],
      "0:15" => [0, 1],
      "0:30" => [0, 2],
      "0:45" => [0, 3],
      "1:00" => [0, 4],
      "2:15" => [0, 9],
      "2:45" => [0, 11],
      "3:00" => [1, 0],
      "3:15" => [1, 1],
      "4:30" => [1, 6],
      "5:30" => [1, 10],
      "6:00" => [2, 0],
      "9:15" => [3, 1],
      "11:45" => [3, 11],
      "12:00" => [4, 0],
      "13:30" => [4, 6],
      "15:30" => [5, 2],
      "18:45" => [6, 3],
      "22:00" => [7, 4],
      "23:30" => [7, 10],
      "23:45" => [7, 11],
    }

    tests.each do |time, answer|
      assert_equal answer, EntryAnalyzer.parse_time(time), "Testing #{time}"
    end
  end

  test ".parse_time handles midnight hour" do
    assert_equal [0, 0], EntryAnalyzer.parse_time("24:00"), "Testing 24:00"
    assert_equal [0, 1], EntryAnalyzer.parse_time("24:15"), "Testing 24:15"
    assert_equal [0, 2], EntryAnalyzer.parse_time("24:30"), "Testing 24:30"
    assert_equal [0, 3], EntryAnalyzer.parse_time("24:45"), "Testing 24:45"
  end

  test ".parse_time raises exception if input is integer only" do
    assert_raises ArgumentError do
      EntryAnalyzer.parse_time("14")
    end
  end

  test ".parse_time raises exception if hour is negative" do
    assert_raises ArgumentError do
      EntryAnalyzer.parse_time("-3:30")
    end
  end

  test ".parse_time raises exception if minute is negative" do
    assert_raises ArgumentError do
      EntryAnalyzer.parse_time("3:-30")
    end
  end

  test ".parse_time raises exception if input is letters" do
    assert_raises ArgumentError do
      EntryAnalyzer.parse_time("foo")
    end
  end

  test ".parse_time raises exception if input is letters with colon" do
    assert_raises ArgumentError do
      EntryAnalyzer.parse_time("foo:bar")
    end
  end

  test ".parse_time raises exception if hour contains letters" do
    assert_raises ArgumentError do
      EntryAnalyzer.parse_time("3x:30")
    end
  end

  test ".parse_time raises exception if nil" do
    assert_raises ArgumentError do
      EntryAnalyzer.parse_time(nil)
    end
  end
 
  #
  # find_by_segment
  #

  test ".find_by_segment finds expected entries only" do

    entry = EntryAnalyzer.find_by_segment(@u1, Date.new(2012, 1, 10), 3)
    assert_equal 51, entry.id
    assert_equal 3, entry.segment

    entry = EntryAnalyzer.find_by_segment(@u2, Date.new(2012, 1, 11), 4)
    assert_equal 58, entry.id
    assert_equal 4, entry.segment
  end

  test ".find_by_segment returns nil if no entries found for time" do
    entry = EntryAnalyzer.find_by_segment(@u2, Date.new(2012, 1, 11), 5)
    assert_nil entry
  end

  test ".find_by_segment raises an exception if more than one entry found" do
    Entry.stub :where, [:a, :b, :c] do
      assert_raises RuntimeError do
        EntryAnalyzer.find_by_segment(@u2, Date.new(2012, 1, 11), 5)
      end
    end
  end

  test ".find_by_segment raises exception if segment nil" do
    assert_raises ArgumentError do
      EntryAnalyzer.find_by_segment(@u1, Date.new(2012, 1, 10), nil)
    end
  end

  test ".find_by_segment raises exception if date is nil" do
    assert_raises ArgumentError do
      EntryAnalyzer.find_by_segment(@u1, nil, 3)
    end
  end

  #
  # find
  #
  # (Yes, most of these duplicate find_by_segment tests, but find_by_segment was a
  #  refactor, so I just kept these.)
  #

  test ".find finds expected entries only" do

    #
    # First three times should all be from same segment
    #
    entry = EntryAnalyzer.find(@u1, Date.new(2012, 1, 10), "9:00")
    assert_equal 51, entry.id
    assert_equal 3, entry.segment

    entry = EntryAnalyzer.find(@u1, Date.new(2012, 1, 10), "9:15")
    assert_equal 51, entry.id

    entry = EntryAnalyzer.find(@u1, Date.new(2012, 1, 10), "11:45")
    assert_equal 51, entry.id

    #
    # As are these next three
    #
    entry = EntryAnalyzer.find(@u2, Date.new(2012, 1, 11), "12:00")
    assert_equal 58, entry.id
    assert_equal 4, entry.segment

    entry = EntryAnalyzer.find(@u2, Date.new(2012, 1, 11), "13:15")
    assert_equal 58, entry.id

    entry = EntryAnalyzer.find(@u2, Date.new(2012, 1, 11), "14:45")
    assert_equal 58, entry.id
  end

  test ".find returns nil if no entries found for time" do
    entry = EntryAnalyzer.find(@u2, Date.new(2012, 1, 11), "15:00")
    assert_nil entry
  end

  test ".find raises an exception if more than one entry found" do
    Entry.stub :where, [:a, :b, :c] do
      assert_raises RuntimeError do
        EntryAnalyzer.find(@u2, Date.new(2012, 1, 11), "15:00")
      end
    end
  end

  test ".find raises exception if time is nil" do
    assert_raises ArgumentError do
      EntryAnalyzer.find(@u1, Date.new(2012, 1, 10), nil)
    end
  end

  test ".find raises exception if time does not parse" do
    assert_raises ArgumentError do
      EntryAnalyzer.find(@u1, Date.new(2012, 1, 10), "badTime")
    end
  end

  test ".find raises exception if date is nil" do
    assert_raises ArgumentError do
      EntryAnalyzer.find(@u1, nil, "9:00")
    end
  end

  #
  # update_segment
  #

  test "update_segment creates a new entry when necessary (with one item)" do
    category = categories(:cat_bob_2)
    test_date = Date.new(2022, 3, 1)
    entries_before = Entry.all.length

    # Make sure this will be a new entry
    assert_nil EntryAnalyzer.find(@u1, test_date, "16:45")

    EntryAnalyzer.update_segment(@u1, test_date, 5, 7, 7, category.id)

    # Verify exactly one new Entry
    assert_equal entries_before + 1, Entry.all.length

    new_entry = EntryAnalyzer.find(@u1, test_date, "16:45")
    # verify that correct category assigned to correct quarter
    (0..11).each do |quarter|
      if quarter == 7
        assert_equal category.id, new_entry.category_id(quarter)
      else
        assert_nil new_entry.category_id(quarter)
      end
    end # loop
  end # test

  test "update_segment creates a new entry when necessary (with several items)" do
    category = categories(:cat_bob_2)
    test_date = Date.new(2022, 3, 1)
    entries_before = Entry.all.length

    # Make sure this will be a new entry
    assert_nil EntryAnalyzer.find(@u1, test_date, "16:45")

    EntryAnalyzer.update_segment(@u1, test_date, 5, 3, 8, category.id)

    # Verify exactly one new Entry
    assert_equal entries_before + 1, Entry.all.length

    new_entry = EntryAnalyzer.find(@u1, test_date, "16:15")
    # verify that correct category assigned to correct quarter
    (0..11).each do |quarter|
      if quarter in (3..8)
        assert_equal category.id, new_entry.category_id(quarter)
      else
        assert_nil new_entry.category_id(quarter)
      end
    end # loop
  end # test


  test "update_segment does not add entry if one exists" do
    test_date = Date.new(2012, 1, 11)
    entries_before = Entry.all.length

    EntryAnalyzer.update_segment(@u1, test_date, 3, 0, 3, categories(:cat_bob_9).id)

    # Verify no new entries
    assert_equal entries_before, Entry.all.length
  end

  test "update_segment modifies only the specified time (quarter)" do
    test_date = Date.new(2012, 1, 11)
    EntryAnalyzer.update_segment(@u1, test_date, 3, 3, 3, categories(:cat_bob_9).id)

    updated_entry = EntryAnalyzer.find(@u1, test_date, "9:45")

    # verify that correct category assigned to correct quarter
    ids = (0..11).map { |quarter| updated_entry.category_id(quarter) }

    assert_equal [1, 2, 3, 9, 3, nil, nil, nil, nil, nil, nil, nil], ids
  end

  test "update_segment modifies only the specified time range" do
    test_date = Date.new(2012, 1, 11)
    EntryAnalyzer.update_segment(@u1, test_date, 3, 3, 6, categories(:cat_bob_9).id)

    updated_entry = EntryAnalyzer.find(@u1, test_date, "9:45")

    # verify that correct category assigned to correct quarter
    ids = (0..11).map { |quarter| updated_entry.category_id(quarter) }

    assert_equal [1, 2, 3, 9, 9, 9, 9, nil, nil, nil, nil, nil], ids
  end

  test "update_segment raises an exception when given a category not owned by the user" do
    test_date = Date.new(2012, 3, 2)

    assert_raises ActiveRecord::RecordInvalid do
      EntryAnalyzer.update_segment(@u1, test_date, 5, 1, 1, categories(:cat_joe_9).id)
    end

    # make sure the record wasn't added to the DB.
    assert_nil EntryAnalyzer.find(@u1, test_date, "16:15")
  end

  test ".update_segment raises an exception if date is string" do
    assert_raises ArgumentError do
      EntryAnalyzer.update_segment(@u1, "bob", 3, 3, 3, categories(:cat_bob_9).id)
    end
  end

  test ".update_segment raises an exception if date is integer" do
    assert_raises ArgumentError do
      EntryAnalyzer.update_segment(@u1, 34323, 3, 3, 3, categories(:cat_bob_9).id)
    end
  end

  #
  # update
  #

  test ".update calls batch_toggle_allowed" do
    skip('Implement me')
  end

  test ".update raises an exception if batch toggle not allowed" do
    EntryAnalyzer.stub :batch_toggle_allowed, false do
      assert_raises ArgumentError do
        EntryAnalyzer.update(@u1, Date.new(2012, 3, 2), nil, "9:45", categories(:cat_bob_9).id)
      end
    end
  end

  test ".update updates exactly one item when start_time is nil"  do
    category = categories(:cat_bob_2)
    test_date = Date.new(2022, 3, 1)

    mock = Minitest::Mock.new
    mock.expect(:call, nil, [@u1, test_date, 5, 7, 7, category.id ])
    EntryAnalyzer.stub(:update_segment, mock) do
      EntryAnalyzer.update(@u1, test_date, nil, "16:45", category.id)
    end
    mock.verify
  end

  test ".update updates range in one segment"  do
    category_id = 2
    test_date = Date.new(2012, 1, 10)

    mock = Minitest::Mock.new
    mock.expect(:call, nil, [@u1, test_date, 4, 4, 10, category_id ])
    EntryAnalyzer.stub(:update_segment, mock) do
      EntryAnalyzer.update(@u1, test_date, "13:00", "14:30", category_id)
    end
    mock.verify
  end

  test ".update handles batch update across two segments (v1)" do
    category_id = 2
    test_date = Date.new(2012, 1, 10)

    mock = Minitest::Mock.new
    mock.expect(:call, nil, [@u1, test_date, 4, 4, 11, category_id ])
    mock.expect(:call, nil, [@u1, test_date, 5, 0, 2, category_id ])
    EntryAnalyzer.stub(:update_segment, mock) do
      EntryAnalyzer.update(@u1, test_date, "13:00", "15:30", category_id)
    end
    mock.verify
  end
  
  test ".update handles batch update across two segments (v2)" do
    category_id = 2
    test_date = Date.new(2012, 1, 10)

    mock = Minitest::Mock.new
    mock.expect(:call, nil, [@u1, test_date, 4, 4, 11, category_id ])
    mock.expect(:call, nil, [@u1, test_date, 5, 0, 9, category_id ])
    EntryAnalyzer.stub(:update_segment, mock) do
      EntryAnalyzer.update(@u1, test_date, "13:00", "17:15", category_id)
    end
    mock.verify
  end


  test ".update handles batch update across three segments"do
  category_id = 2
    test_date = Date.new(2012, 1, 10)

    mock = Minitest::Mock.new
    mock.expect(:call, nil, [@u1, test_date, 4, 4, 11, category_id ])
    mock.expect(:call, nil, [@u1, test_date, 5, 0, 9, category_id ])
    EntryAnalyzer.stub(:update_segment, mock) do
      EntryAnalyzer.update(@u1, test_date, "13:00", "17:15", category_id)
    end
    mock.verify
end
  

  #
  # .batch_toggle_allowed
  #

  test ".batch_toggle_allowed returns true if start_time is nil" do
    assert EntryAnalyzer.batch_toggle_allowed("user", "date", nil, "the_time", "cat_id")
  end

  test ".batch_toggle_allowed returns false if start equals end" do
    assert_not EntryAnalyzer.batch_toggle_allowed("user", "date", "6:30", "6:30", "cat_id")
  end

  test ".batch_toggle_allowed returns false if end immediately before start" do
    assert_not EntryAnalyzer.batch_toggle_allowed("user", "date", "6:30", "6:15", "cat_id")
  end

  test ".batch_toggle_allowed returns false if end before start in same block" do
    assert_not EntryAnalyzer.batch_toggle_allowed("user", "date", "8:15", "6:15", "cat_id")
  end

  test ".batch_toggle_allowed returns false if end before start in previous block" do
    assert_not EntryAnalyzer.batch_toggle_allowed("user", "date", "13:15", "11:45", "cat_id")
  end

  test ".batch_toggle_allowed returns false if end before start in much earlier block" do
    assert_not EntryAnalyzer.batch_toggle_allowed("user", "date", "17:30", "6:45", "cat_id")
  end

  #
  # Batch fill
  #

  test ".batch_toggle_allowed returns false if start not nil and category not start" do
    # shift-click must be on the same category line as the previous click
    make(61, @u2, 2012, 1, 12, 3, [nil, nil, 12, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:30", "12:30", 13)
  end

  test ".batch_toggle_allowed returns false if both start and end filled with same category (same block)" do
    # if the previous click filled a bubble, the shift-click can't be on a bubble that is already full.
    make(61, @u2, 2012, 1, 12, 3, [nil, nil, 12, nil, nil, nil, nil, nil, nil, nil, nil, 12])
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:30", "11:45", 12)
  end

  test ".batch_toggle_allowed returns false if both start and end filled with same category (different block)" do
    # if the previous click filled a bubble, the shift-click can't be on a bubble that is already full.
    make(61, @u2, 2012, 1, 12, 3, [nil, nil, 12, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, 12, nil, nil, nil, nil, nil, nil, nil, nil])
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:30", "12:45", 12)
  end

  test ".batch_toggle_allowed returns false if both start and end filled but with different categories (same block)" do
    # if the previous click filled a bubble, the shift-click can't be on a bubble that is already full.
    make(61, @u2, 2012, 1, 12, 3, [nil, nil, 12, nil, nil, nil, nil, nil, nil, 13])
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:30", "11:15", 12)
  end

  test ".batch_toggle_allowed returns false if both start and end filled but with different categories (different block)" do
    # if the previous click filled a bubble, the shift-click can't be on a bubble that is already full.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, 13, nil, nil, nil, nil, nil, nil, nil])
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "13:00", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with same category (same block)" do
    # All bubbles between start and end must be empty.
    make(61, @u2, 2012, 1, 12, 3, [nil, nil, 12, nil, nil, nil, nil, nil, 12])  # 12 is at 11:00
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:30", "11:15", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with different category (same block)" do
    # All bubbles between start and end must be empty.
    make(61, @u2, 2012, 1, 12, 3, [nil, nil, 12, nil, nil, nil, nil, nil, 13]) # 13 is at 11:00
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:30", "11:15", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with same category (start block / no end block)" do
    # All bubbles between start and end must be empty.
    # For this test, the end time is still empty, but there isn't yet a record for that block.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, 12, nil, nil, nil, nil])
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "13:00", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with same category (start block / end block exists)" do
    # All bubbles between start and end must be empty.
    # For this test, the end time is still empty, but later times in that block are full.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, 12, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, nil, 13, nil, nil, nil, nil, nil, nil]) # 13 is at 1:15
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "13:00", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with different category (start block / no end block)" do
    # All bubbles between start and end must be empty.
    # For this test, the end time is still empty, but there isn't yet a record for that block.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, 13, nil])
    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "13:00", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with different category (start block / end block exists)" do
    # All bubbles between start and end must be empty.
    # For this test, the end time is still empty, but later times in that block are full.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil, 13])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, nil, 13, nil, nil, nil, nil, nil, nil]) # 13 is at 1:15

    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "13:00", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with same category (middle block / end not created)" do
    # All bubbles between start and end must be empty.
    # For this test, the end time is still empty, but there isn't yet a record for that block.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, nil, 12, nil, nil, nil, nil, nil, nil])

    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "15:45", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with different category (middle block / end not created)" do
    # All bubbles between start and end must be empty.
    # For this test, the end time is still empty, but there isn't yet a record for that block.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, nil, 13, nil, nil, nil, nil, nil, nil])

    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "15:45", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with same category (middle block / end created)" do
    # All bubbles between start and end must be empty.
    # For this test, the end time is still empty, but later times in that block are full.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, 12, nil, nil, nil, nil, nil, nil, nil])
    make(63, @u2, 2012, 1, 12, 5, [nil, nil, nil, nil, nil, nil, 13, nil, nil, nil, nil]) # 13 is at 16:15

    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "15:45", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with different category (middle block / end created)" do
    # All bubbles between start and end must be empty.
    # For this test, the end time is still empty, but later times in that block are full.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, 13, nil, nil, nil, nil, nil, nil, nil])
    make(63, @u2, 2012, 1, 12, 5, [nil, nil, nil, nil, nil, nil, 13, nil, nil, nil, nil]) # 13 is at 16:15

    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "15:45", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with same category (end block / middle not created)" do
    # All bubbles between start and end must be empty.
    # For this test, the middle block is empty, but hasn't been created.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 5, [nil, 12, nil, nil, nil, nil, 13, nil, nil, nil, nil]) # 13 is at 16:15

    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "15:30", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with same category (end block / middle created)" do
    # All bubbles between start and end must be empty.
    # For this test, the middle block is empty
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    make(63, @u2, 2012, 1, 12, 5, [nil, 12, nil, nil, nil, nil, 13, nil, nil, nil, nil]) # 13 is at 16:15

    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "15:30", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with different category (end block / middle not created)" do
    # All bubbles between start and end must be empty.
    # For this test, the middle block is empty, but hasn't been created.
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 5, [nil, 13, nil, nil, nil, nil, 13, nil, nil, nil, nil]) # 13 is at 16:15

    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "15:30", 12)
  end

  test ".batch_toggle_allowed returns false if start filled and some middle time filled with different category (end block / middle created)" do
    # All bubbles between start and end must be empty.
    # For this test, the middle block is empty
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    make(63, @u2, 2012, 1, 12, 5, [nil, 13, nil, nil, nil, nil, 13, nil, nil, nil, nil]) # 13 is at 16:15

    d = Date.new(2012, 1, 12)
    assert_not EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "15:30", 12)
  end

  test ".batch_toggle_allowed returns true if start filled and all unfilled until end in same block" do
    make(61, @u2, 2012, 1, 12, 3, [nil, 12, nil, nil, nil, nil, nil, nil, nil, nil, nil, 13]) # 13 is at 11:45
    d = Date.new(2012, 1, 12)
    assert EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:15", "11:30", 12)
  end

  test ".batch_toggle_allowed returns true if start filled and all unfilled until end in adjacent blocks" do
    make(61, @u2, 2012, 1, 12, 3, [13, 13, 12, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, nil, nil, nil, nil, nil, 12, nil, nil]) # 12 is at 14:15
    d = Date.new(2012, 1, 12)
    assert EntryAnalyzer.batch_toggle_allowed(@u2, d, "9:30", "14:00", 12)
  end

  test ".batch_toggle_allowed returns true if start filled and and all unfilled until end several blocks apart with missing blocks" do
    make(61, @u2, 2012, 1, 12, 2, [13, 13, 12, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 6, [nil, nil, nil, nil, nil, 12, nil, nil, nil, 12, nil, nil]) # 12 is at 19:15
    d = Date.new(2012, 1, 12)
    assert EntryAnalyzer.batch_toggle_allowed(@u2, d, "6:30", "19:00", 12)
  end

  test ".batch_toggle_allowed returns true if start filled and and all unfilled until end several blocks apart with several missing blocks" do
    make(61, @u2, 2012, 1, 12, 2, [13, 13, 12, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 4, [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    make(63, @u2, 2012, 1, 12, 6, [nil, nil, nil, nil, nil, 12, nil, nil, nil, 12, nil, nil]) # 12 is at 19:15
    d = Date.new(2012, 1, 12)
    assert EntryAnalyzer.batch_toggle_allowed(@u2, d, "6:30", "19:00", 12)
  end

  test ".batch_toggle_allowed returns true if start filled and and all unfilled until end several blocks apart with several missing blocks (v2)" do
    make(61, @u2, 2012, 1, 12, 2, [13, 13, 12, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    make(62, @u2, 2012, 1, 12, 3, [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil])
    make(63, @u2, 2012, 1, 12, 6, [nil, nil, nil, nil, nil, 12, nil, nil, nil, 12, nil, nil]) # 12 is at 19:15
    d = Date.new(2012, 1, 12)
    assert EntryAnalyzer.batch_toggle_allowed(@u2, d, "6:30", "19:00", 12)
  end

  #
  # Batch unfill
  #

  # test ".batch_toggle_allowed returns false if both start and end both unfilled"

  # test ".batch_toggle_allowed returns false if start unfilled and some middle time unfilled (same block)"

  # test ".batch_toggle_allowed returns false if start unfilled and some middle time unfilled (start block)"

  # test ".batch_toggle_allowed returns false if start unfilled and some middle time unfilled (middle block)"

  # test ".batch_toggle_allowed returns false if start unfilled and some middle time unfilled (end block)"

  # test ".batch_toggle_allowed returns true if start unfilled and all until end filled in same block"

  # test ".batch_toggle_allowed returns true if start unfilled and all until end filled in adjacent block"

  # test ".batch_toggle_allowed returns true if start unfilled and all until end filled several blocks apart"
end
```

**Comment by kzkn** [comment]
@kurmasz 
Thanks for the report.
I've confirmed that works fine with the latest version of Rufo. Please give it try.

```
$ rufo --version
rufo 0.17.0
$ ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x86_64-linux]
$ cat foo.rb
# your code here
$ rufo foo.rb
Format: foo.rb
```

**Comment by kurmasz** [comment]
I see what I did wrong: I checked the version of htmlbeautifier, but forgot to also check the rufo version.

Sorry about that.
