### ISSUE TITLE
`bug': Expected token on_ident, not on_words_sep at

### ISSUE THREAD

**Issue by anatol** [ruby-formatter/rufo#72]
Hello,

I am trying to use `rufo` tool at Arch Linux to format [following file](https://git.archlinux.org/svntogit/community.git/plain/trunk/generate_build.rb?h=packages/android-tools) I get a `bug` error from the script:

```
$ rufo ./generate_build.rb 
You've found a bug!
It happened while trying to format the file ./generate_build.rb
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it

Traceback (most recent call last):
	24: from /usr/bin/rufo:23:in `<main>'
	23: from /usr/bin/rufo:23:in `load'
	22: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/exe/rufo:4:in `<top (required)>'
	21: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:12:in `run'
	20: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:40:in `run'
	19: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:81:in `format_args'
	18: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:81:in `each'
	17: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:82:in `block in format_args'
	16: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:124:in `format_file'
	15: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:165:in `format'
	14: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:166:in `format'
	13: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:187:in `visit'
	12: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `visit_exps'
	11: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each_with_index'
	10: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each'
	 9: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:502:in `block in visit_exps'
	 8: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3563:in `push_node'
	 7: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:503:in `block (2 levels) in visit_exps'
	 6: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:309:in `visit'
	 5: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:738:in `visit_assign'
	 4: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:279:in `visit'
	 3: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:273:in `visit'
	 2: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:2990:in `consume_token'
	 1: from /usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3424:in `check'
/usr/lib/ruby/gems/2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3429:in `bug': Expected token on_ident, not on_words_sep at [[86, 28], :on_words_sep, "\n", #<Ripper::Lexer::State: EXPR_BEG>] (Rufo::Bug)
```

**Comment by gingermusketeer** [comment]
It looks like this is coming from somewhere around here:
```
puts """
rule cc
  command = $CC $cflags -c $in -o $out

rule cxx
  command = $CXX $cflags -c $in -o $out

rule link
  command = $CXX $ldflags $LDFLAGS $in -o $out


"""

adbdfiles = %w(
  adb.cpp
  adb_io.cpp
  adb_listeners.cpp
  adb_trace.cpp
  adb_utils.cpp
  bugreport.cpp
  line_printer.cpp
  sockets.cpp
  transport.cpp
  transport_local.cpp
  transport_usb.cpp
  transport_mdns_unsupported.cpp
  fdevent.cpp
  adb_auth_host.cpp
  shell_service_protocol.cpp
)
libadbd = compile(expand('core/adb', adbdfiles), '-DADB_VERSION="\"$PKGVER\"" -DADB_HOST=1 -Icore/include -Icore/base/include -Icore/adb -Icore/libcrypto_utils/include -Iboringssl/include')
```

Line in particular looks to be, based on line number in exception, the line with `shell_service_protocol.cpp`

**Comment by mjago** [comment]
Fixed in HEAD
