### ISSUE TITLE
Bug: Expected token on_comma, not on_words_sep

### ISSUE THREAD

**Issue by ivoanjo** [ruby-formatter/rufo#85]
While looking into #83 I tried rufo on a number of repositories for commonly-used gems and came across a few issues.

This one comes from the [arel](https://github.com/rails/arel) gem.

Traceback:

```
Traceback (most recent call last):
        99: from .rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
        98: from .rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
        97: from .rvm/gems/ruby-2.5.0/bin/rufo:23:in `<main>'
        96: from .rvm/gems/ruby-2.5.0/bin/rufo:23:in `load'
        95: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/exe/rufo:4:in `<top (required)>'
        94: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:12:in `run'
        93: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:40:in `run'
        92: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:81:in `format_args'
        91: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:81:in `each'
        90: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:82:in `block in format_args'
        89: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:124:in `format_file'
        88: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/command.rb:165:in `format'
        87: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:166:in `format'
        86: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:187:in `visit'
        85: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `visit_exps'
        84: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each_with_index'
        83: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each'
        82: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:502:in `block in visit_exps'
        81: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3563:in `push_node'
        80: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:503:in `block (2 levels) in visit_exps'
        79: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:383:in `visit'
        78: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1885:in `visit_module'
        77: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3578:in `push_type'
        76: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1892:in `block in visit_module'
        75: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:363:in `visit'
        74: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1480:in `visit_bodystmt'
        73: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3321:in `indent_body'
        72: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3246:in `indent'
        71: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3322:in `block in indent_body'
        70: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `visit_exps'
        69: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each_with_index'
        68: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each'
        67: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:502:in `block in visit_exps'
        66: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3563:in `push_node'
        65: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:503:in `block (2 levels) in visit_exps'
        64: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:351:in `visit'
        63: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1268:in `visit_call_with_block'
        62: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:357:in `visit'
        61: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1337:in `visit_do_block'
        60: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1480:in `visit_bodystmt'
        59: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3321:in `indent_body'
        58: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3246:in `indent'
        57: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3322:in `block in indent_body'
        56: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `visit_exps'
        55: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each_with_index'
        54: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each'
        53: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:502:in `block in visit_exps'
        52: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3563:in `push_node'
        51: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:503:in `block (2 levels) in visit_exps'
        50: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:351:in `visit'
        49: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1268:in `visit_call_with_block'
        48: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:357:in `visit'
        47: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1337:in `visit_do_block'
        46: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1480:in `visit_bodystmt'
        45: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3321:in `indent_body'
        44: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3246:in `indent'
        43: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3322:in `block in indent_body'
        42: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `visit_exps'
        41: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each_with_index'
        40: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each'
        39: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:502:in `block in visit_exps'
        38: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3563:in `push_node'
        37: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:503:in `block (2 levels) in visit_exps'
        36: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:351:in `visit'
        35: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1268:in `visit_call_with_block'
        34: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:357:in `visit'
        33: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1337:in `visit_do_block'
        32: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1480:in `visit_bodystmt'
        31: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3321:in `indent_body'
        30: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3246:in `indent'
        29: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3322:in `block in indent_body'
        28: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `visit_exps'
        27: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each_with_index'
        26: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each'
        25: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:502:in `block in visit_exps'
        24: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3563:in `push_node'
        23: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:503:in `block (2 levels) in visit_exps'
        22: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:309:in `visit'
        21: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:743:in `visit_assign'
        20: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:812:in `visit_assign_value'
        19: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3413:in `indent_after_space'
        18: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:336:in `visit'
        17: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1162:in `visit_command_call'
        16: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1217:in `visit_command_args'
        15: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3242:in `indent'
        14: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1218:in `block in visit_command_args'
        13: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `visit_exps'
        12: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each_with_index'
        11: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:483:in `each'
        10: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:502:in `block in visit_exps'
         9: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3563:in `push_node'
         8: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:503:in `block (2 levels) in visit_exps'
         7: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:338:in `visit'
         6: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1417:in `visit_call_args'
         5: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1685:in `visit_comma_separated_list'
         4: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1685:in `each_with_index'
         3: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1685:in `each'
         2: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:1697:in `block in visit_comma_separated_list'
         1: from .rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3424:in `check'
.rvm/gems/ruby-2.5.0/gems/rufo-0.2.0/lib/rufo/formatter.rb:3429:in `bug': Expected token on_comma, not on_words_sep at [[15, 47], :on_words_sep, " ", #<Ripper::Lexer::State: EXPR_ARG>] (Rufo::Bug)
```

File that triggers the issue: <https://raw.githubusercontent.com/rails/arel/eb3f968b5ffdd3b343e7d190f1aa0b36864f56a2/test/test_insert_manager.rb>

**Comment by gingermusketeer** [comment]
It looks like this issue has been resolved on master. Hopefully we can get a release out soon.

**Comment by mjago** [comment]
Fixed in HEAD
