### ISSUE TITLE
Bug: Keyword arguments aren't supported

### ISSUE THREAD

**Issue by alem0lars** [ruby-formatter/rufo#89]
Formatting the following file:

```ruby
def putit!(**args)
  puts(**args)
end

putit!(a:1,b:2)
```

Gives the following error:

```
You've found a bug!
It happened while trying to format the file foo.rb
Please report it to https://github.com/ruby-formatter/rufo/issues with code that triggers it

bundler: failed to load command: rufo (/data/projects/personal/chips/vendor/bundle/ruby/2.5.0/bin/rufo)
Rufo::Bug: Unhandled node: kwrest_param at [[1, 13], :on_ident, "args", #<Ripper::Lexer::State: EXPR_ARG>]
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:3507:in `bug'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:463:in `visit'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:2074:in `visit_params'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:390:in `visit'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:1959:in `block in visit_def_from_name'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:3312:in `indent'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:1958:in `visit_def_from_name'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:1899:in `block in visit_def'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:3707:in `push_hash'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:1898:in `visit_def'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:384:in `visit'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:492:in `block (2 levels) in visit_exps'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:3699:in `push_node'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:491:in `block in visit_exps'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:472:in `each'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:472:in `each_with_index'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:472:in `visit_exps'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:187:in `visit'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/formatter.rb:163:in `format'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/command.rb:127:in `format'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/command.rb:85:in `format_file'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/command.rb:68:in `block in format_args'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/command.rb:67:in `each'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/command.rb:67:in `format_args'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/command.rb:25:in `run'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/lib/rufo/command.rb:12:in `run'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/gems/rufo-0.1.0/exe/rufo:4:in `<top (required)>'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/bin/rufo:23:in `load'
  /data/projects/personal/chips/vendor/bundle/ruby/2.5.0/bin/rufo:23:in `<top (required)>'
```

**Comment by alem0lars** [comment]
I was using an old version of rufo, my bad xD
